### ISSUE TITLE
how to open a camera ??

### ISSUE THREAD

**Issue by zsz00** [IHPSystems/Cameras.jl#2]
can you give a exmple that to open the laptop camera ??

**Comment by stemann** [comment]
The Cameras package is meant to provide an interface to cameras - not a (hardware-specific) implementation: This is left to packages such as VideoIO.jl and Spinnaker.jl.

For now, if you need to access your built-in camera, VideoIO.jl is probably the way forward:
https://github.com/kmsquire/VideoIO.jl
