### ISSUE TITLE
overlapping role of camera constructor and 'open!'

### ISSUE THREAD

**Issue by ehgus** [IHPSystems/Cameras.jl#7]
Hi, I faced some problem while distinguishing the role of camera constructor and `open!` function. For the best of my knowledge, the lifecycle of the camera is as follows:

open camera ---> (some setting such as roi, exposure...) ---> start camera ---> take images ---> stop camera ---> close camera

According to the logic, the initialization and opening camera are coupled so that camera constructor and `open!` function cannot be decoupled logically to me. Could you give an opinion to handle this issue?

**Comment by stemann** [comment]
The camera constructor should give you an object (a value) that you can then call `open!` on, and subsequently configure - the concepts of opening and configuring should be separate (but configuring requires first opening the camera).

**Comment by ehgus** [comment]
Thank you for your suggestion. Then I can summarize the roles of each step in the following way:

1. struct initialization: configuration
2. open camera: connect the camera according to the configuration
3. start camera: do acquisition / ready for acquisition
4. stop camera: stop the acquisition
5. close camera: disconnect the camera

Some configurations must be determined in the initialization.
Other configurations are set to default at the initialization and customized later.

Now it looks clear to me. I will close the issue if you agree with my summary.
Thank you!

**Comment by stemann** [comment]
I would actually say that construction/struct initialization will yield some level of configuration (e.g. the device ID/address), opening will put the camera in an open state that allows for further configuration, e.g. setting exposure time.

Feel free to close this issue.
